name = "ai-content-detector"
main = "src/index.tsx"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"

# Cloudflare AI binding
[ai]
binding = "AI"

# Production environment variables
[vars]
ENVIRONMENT = "production"

# Preview environment for pull requests
[env.preview]
name = "preview-ai-content-detector"
vars = { ENVIRONMENT = "preview" }
