name = "ai-content-detector"
main = "src/index.tsx"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"

# Cloudflare AI binding
[ai]
binding = "AI"

# KV namespace for rate limiting
# Run: wrangler kv:namespace create "RATE_LIMITER"
# Then update the IDs below
[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "YOUR_KV_NAMESPACE_ID"  # Replace with: wrangler kv:namespace create "RATE_LIMITER"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"  # Replace with: wrangler kv:namespace create "RATE_LIMITER" --preview

# Production environment variables
[vars]
ENVIRONMENT = "production"

# Preview environment for pull requests
[env.preview]
name = "preview-ai-content-detector"
vars = { ENVIRONMENT = "preview" }
