blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/ckorhonen/ai-content-detector/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issue
    url: https://github.com/ckorhonen/ai-content-detector/security/advisories/new
    about: Report a security vulnerability privately
